# Generated by Django 5.0.7 on 2025-03-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_tag',
            field=models.CharField(blank=True, choices=[('Featured Products', 'Featured Products'), ('Bestsellers', 'Bestsellers'), ('Popular Categories', 'Popular Categories'), ('New Arrivals', 'New Arrivals'), ('Sale', 'Sale'), ('Top Rated', 'Top Rated')], max_length=50, null=True),
        ),
    ]
