# Generated by Django 5.2 on 2025-05-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_product_dimensions_remove_product_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('ultrabook', 'Ultrabooks'), ('gaming', 'Gaming Laptops'), ('business', 'Business Laptops'), ('convertible', '2-in-1 Convertibles'), ('chromebook', 'Chromebooks'), ('budget', 'Budget Laptops')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('Audio Equipment', 'Audio Equipment'), ('Accessories', 'Accessories'), ('Components', 'Components')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Units in stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reviews_in_stars',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Average star rating (e.g. 4.5)', max_digits=2),
        ),
    ]
